# Site settings
title: Curriculum Vitae Thomas Vanneuville
name: Thomas Vanneuville-

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/tvanneuville
 - title: LinkedIn
   url: https://www.linkedin.com/in/thomasvanneuville/

#Any buzzword skills you want to include
skills:
 - Python
 - Flask
 - SQL
 - Linux
 - HTML
 - CSS
 - SASS

#Work experience is required
roles:
 - title: Inernship Bio-Informatics
   start: April 2018 
   end: June 2018
   employer: Centrum Medische Genetica Gent
   description: Development of a responsive interface for RNA database LNCipedia.
 - title: Lab Technician Microbiology
   start: Dec 2016
   end: Sep 2017
   employer: Medisch Labo Bruyland Kortrijk
   description: Lab technician Microbiology
 - title: Lab Techician Microbiology
   start: Feb 2016
   end: Dec 2016
   employer: AZ Damiaan Oostende
   description: Lab Techician Microbiology

#Education is required
education:
 - level: Advanced Bachelor
   date: 2017
   subject: Bio-Informatics
   school: Hogeschool West-Vlaanderen
 - level: Bachelor of Applied Science 
   date: 2012
   subject: Medical Laboratory Technology
   school: Hogeschool Vives Noord

#List of interesting Github repo/projects to include - optional
github:
 - tvanneuville/warframe-alerts
 - tvanneuville/Trouw
 - tvanneuville/find-conservation

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <a target='_blank' href="https://trouw-app-heroku.herokuapp.com/"><strong>Trouw webapp</strong></a>: Because managing invitations for a wedding can be a exhausting task, I am working on a webapplication in Flask that will make this a lot easier! <br/><br/>
   
   <a target='_blank' href="http://35.204.95.41/"><strong>LNCipedia </strong></a>: During my Internship i worked on lncipedia. LNCipedia is an online database that is highly used in cancer research. This website is built on Mojolicious, a Perl framework. I made a new responsive interface for LNCipedia. I also made a Webapp from a tool i developed there <a target='_blank' href="https://find-conservation.herokuapp.com/"> find conservation app </a><br/><br/>
   
   <strong>Linux and Raspberry Pie</strong>: Because i am a nerd, I enjoy fooling around with my Raspberry Pie. I wrote a script that records my favorite podcast: 'de filefuif' op studio brussel. And i also wrote a script to detect <a target='_blank' href="https://github.com/tvanneuville/warframe-alerts"> Warframe alerts</a>. 
   
